version: '3.7'

services:
  salesdb:
    build:
      dockerfile: ./.docker/mysql.dockerfile
      context: .
    image: sales/db
    container_name: salesdb
    volumes:
      - ./.docker/data:/app
    ports:
      - '3306:3306'
    networks:
      - sales-network

      

  sales-app:
    container_name: sales-app
    build: .
    image: sales/app
    restart: on-failure
    volumes:
      - .:/usr/app
       - .:/usr/app/node_modules
    ports:
      - '3333:3333'
    env_file:
      - .env
    networks:
      - sales-network
    depends_on:
      - 'salesdb'

networks:
  sales-network:
    driver: bridge




